version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 qazdrive.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      - DEBUG=0
      - SECRET_KEY=your-secret-key-here
      - DATABASE_URL=postgres://postgres:postgres@db:5432/qazdrive
      - ALLOWED_HOSTS=localhost,127.0.0.1,sapapdd.kz,www.sapapdd.kz
      - EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend

  nginx:
    image: nginx:1.25
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=qazdrive
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data:
  static_volume:
  media_volume: